---
- name: MySQL preseed
  action: debconf name=mysql-server question='{{ item }}' vtype='password' value='{{ ansible_mysql_password }}'
  with_items:
   - mysql-server/root_password
   - mysql-server/root_password_again

- name: Install MySQL
  apt: pkg=mysql-server state=present


